// convert all the "en" map keys to other languages, you can update the keys map in the Messages class as follows:

// en,  tr , fr , es, de, it, ja, ar, ru, zh , pt , hi , ms , ko , id

class TranslateHelper {
  static Map<String, Map<String, String>> getHelperTranslations() {
    return {
      "en": {
        "Settings": "Settings",
        "Remove Limits": "Remove Limits",
        "Check out this amazing app at": "Check out this amazing app at",
        "Remaining": "Remaining",
        "Daily Limit": "Daily Limit",
        "Share with Friends": "Share with Friends",
        "Rate Us": "Rate Us",
        "Privacy Policy": "Privacy Policy",
        "Terms of Use (EULA)": "Terms of Use (EULA)",
        "Image saved to photos": "Image saved to photos",
        "Save to Photos": "Save to Photos",
        "Search": "Search",
        "Share": "Share",
        "Save": "Save",
        "Watch ad": "Watch ad",
        "CONTINUE": "CONTINUE",
        "3 DAYS FREE": "3 DAYS FREE",
        "DISCOUNT": "DISCOUNT",
        "months": "months",
        "month": "month",
        "MOST POPULAR": "MOST POPULAR",
        "then": "then",
        "Payment successful": "Payment successful",
        "You are using PREMIUM version of app now":
            "You are using PREMIUM version of app now",
        "Success": "Success",
        "SUCCESS": "SUCCESS",
        "ERROR": "ERROR",
        "Error": "Error",
        "You have no active subscription.": "You have no active subscription.",
        "Buy Premium": "Buy Premium",
        "Restore Purchases": "Restore Purchases",
        "You are using the premium version of this app.":
            "You are using the premium version of this app."
      },
      "tr": {
        "Settings": "Ayarlar",
        "Remove Limits": "Sınırları Kaldır",
        "Check out this amazing app at":
            "Bu harika uygulamayı burada kontrol edin",
        "Remaining": "Kalan",
        "Daily Limit": "Günlük Limit",
        "Share with Friends": "Arkadaşlarla Paylaş",
        "Rate Us": "Bize Puan Ver",
        "Privacy Policy": "Gizlilik Politikası",
        "Terms of Use (EULA)": "Kullanım Koşulları (EULA)",
        "Image saved to photos": "Fotoğraf fotoğraflara kaydedildi",
        "Save to Photos": "Fotoğraflara Kaydet",
        "Search": "Ara",
        "Share": "Paylaş",
        "Save": "Kaydet",
        "Watch ad": "Reklamı İzle",
        "CONTINUE": "DEVAM ET",
        "3 DAYS FREE": "3 GÜNLÜK ÜCRETSİZ",
        "DISCOUNT": "İNDİRİM",
        "months": "ay",
        "month": "ay",
        "MOST POPULAR": "EN POPÜLER",
        "then": "ardından",
        "Payment successful": "Ödeme başarılı",
        "You are using PREMIUM version of app now":
            "Şu anda uygulamanın PREMİUM sürümünü kullanıyorsunuz",
        "Success": "Başarılı",
        "SUCCESS": "BAŞARILI",
        "ERROR": "HATA",
        "Error": "Hata",
        "You have no active subscription.":
            "Aktif bir aboneliğiniz bulunmamaktadır.",
        "Buy Premium": "Premium Satın Al",
        "Restore Purchases": "Satın Alımları Geri Yükle",
        "You are using the premium version of this app.":
            "Bu uygulamanın premium sürümünü kullanıyorsunuz."
      },
      "fr": {
        "Settings": "Paramètres",
        "Remove Limits": "Supprimer les Limites",
        "Check out this amazing app at":
            "Découvrez cette incroyable application sur",
        "Remaining": "Restant",
        "Daily Limit": "Limite quotidienne",
        "Share with Friends": "Partager avec des Amis",
        "Rate Us": "Évaluez-nous",
        "Privacy Policy": "Politique de Confidentialité",
        "Terms of Use (EULA)": "Conditions d'Utilisation (CLUF)",
        "Image saved to photos": "Image enregistrée dans les photos",
        "Save to Photos": "Enregistrer dans les Photos",
        "Search": "Rechercher",
        "Share": "Partager",
        "Save": "Enregistrer",
        "Watch ad": "Regarder la Publicité",
        "CONTINUE": "CONTINUER",
        "3 DAYS FREE": "3 JOURS GRATUITS",
        "DISCOUNT": "RÉDUCTION",
        "months": "mois",
        "month": "mois",
        "MOST POPULAR": "LE PLUS POPULAIRE",
        "then": "puis",
        "Payment successful": "Paiement réussi",
        "You are using PREMIUM version of app now":
            "Vous utilisez maintenant la version PREMIUM de l'application",
        "Success": "Succès",
        "SUCCESS": "SUCCÈS",
        "ERROR": "ERREUR",
        "Error": "Erreur",
        "You have no active subscription.":
            "Vous n'avez aucune souscription active.",
        "Buy Premium": "Acheter Premium",
        "Restore Purchases": "Restaurer les Achats",
        "You are using the premium version of this app.":
            "Vous utilisez la version premium de cette application."
      },
      "es": {
        "Settings": "Configuración",
        "Remove Limits": "Eliminar Límites",
        "Check out this amazing app at":
            "Descubre esta increíble aplicación en",
        "Remaining": "Restante",
        "Daily Limit": "Límite Diario",
        "Share with Friends": "Compartir con Amigos",
        "Rate Us": "Califícanos",
        "Privacy Policy": "Política de Privacidad",
        "Terms of Use (EULA)": "Términos de Uso (EULA)",
        "Image saved to photos": "Imagen guardada en fotos",
        "Save to Photos": "Guardar en Fotos",
        "Search": "Buscar",
        "Share": "Compartir",
        "Save": "Guardar",
        "Watch ad": "Ver Anuncio",
        "CONTINUE": "CONTINUAR",
        "3 DAYS FREE": "3 DÍAS GRATIS",
        "DISCOUNT": "DESCUENTO",
        "months": "meses",
        "month": "mes",
        "MOST POPULAR": "MÁS POPULAR",
        "then": "luego",
        "Payment successful": "Pago Exitoso",
        "You are using PREMIUM version of app now":
            "Estás utilizando ahora la versión PREMIUM de la aplicación",
        "Success": "Éxito",
        "SUCCESS": "ÉXITO",
        "ERROR": "ERROR",
        "Error": "Error",
        "You have no active subscription.": "No tienes una suscripción activa.",
        "Buy Premium": "Comprar Premium",
        "Restore Purchases": "Restaurar Compras",
        "You are using the premium version of this app.":
            "Estás utilizando la versión premium de esta aplicación."
      },
      "de": {
        "Settings": "Einstellungen",
        "Remove Limits": "Limits entfernen",
        "Check out this amazing app at":
            "Schau dir diese großartige App an unter",
        "Remaining": "Verbleibend",
        "Daily Limit": "Tageslimit",
        "Share with Friends": "Mit Freunden teilen",
        "Rate Us": "Bewerte uns",
        "Privacy Policy": "Datenschutzbestimmungen",
        "Terms of Use (EULA)": "Nutzungsbedingungen (EULA)",
        "Image saved to photos": "Bild in Fotos gespeichert",
        "Save to Photos": "In Fotos speichern",
        "Search": "Suchen",
        "Share": "Teilen",
        "Save": "Speichern",
        "Watch ad": "Werbeanzeige ansehen",
        "CONTINUE": "FORTSETZEN",
        "3 DAYS FREE": "3 TAGE KOSTENLOS",
        "DISCOUNT": "RABATT",
        "months": "Monate",
        "month": "Monat",
        "MOST POPULAR": "AM BELIEBTESTEN",
        "then": "dann",
        "Payment successful": "Zahlung erfolgreich",
        "You are using PREMIUM version of app now":
            "Du verwendest jetzt die PREMIUM-Version dieser App",
        "Success": "Erfolg",
        "SUCCESS": "ERFOLG",
        "ERROR": "FEHLER",
        "Error": "Fehler",
        "You have no active subscription.": "Du hast kein aktives Abonnement.",
        "Buy Premium": "Premium kaufen",
        "Restore Purchases": "Käufe wiederherstellen",
        "You are using the premium version of this app.":
            "Du verwendest die Premium-Version dieser App."
      },
      "it": {
        "Settings": "Impostazioni",
        "Remove Limits": "Rimuovi Limiti",
        "Check out this amazing app at": "Scopri questa fantastica app su",
        "Remaining": "Rimasto",
        "Daily Limit": "Limite Giornaliero",
        "Share with Friends": "Condividi con Amici",
        "Rate Us": "Vota",
        "Privacy Policy": "Informativa sulla Privacy",
        "Terms of Use (EULA)": "Termini di Utilizzo (EULA)",
        "Image saved to photos": "Immagine salvata nelle foto",
        "Save to Photos": "Salva nelle Foto",
        "Search": "Cerca",
        "Share": "Condividi",
        "Save": "Salva",
        "Watch ad": "Guarda Annuncio",
        "CONTINUE": "CONTINUA",
        "3 DAYS FREE": "3 GIORNI GRATIS",
        "DISCOUNT": "SCONTO",
        "months": "mesi",
        "month": "mese",
        "MOST POPULAR": "PIÙ POPOLARE",
        "then": "poi",
        "Payment successful": "Pagamento effettuato con successo",
        "You are using PREMIUM version of app now":
            "Stai utilizzando la versione PREMIUM di questa app",
        "Success": "Successo",
        "SUCCESS": "SUCCESSO",
        "ERROR": "ERRORE",
        "Error": "Errore",
        "You have no active subscription.":
            "Non hai una sottoscrizione attiva.",
        "Buy Premium": "Acquista Premium",
        "Restore Purchases": "Ripristina Acquisti",
        "You are using the premium version of this app.":
            "Stai utilizzando la versione premium di questa app."
      },
      "ja": {
        "Settings": "設定",
        "Remove Limits": "制限解除",
        "Check out this amazing app at": "この素晴らしいアプリをチェック",
        "Remaining": "残り",
        "Daily Limit": "1日の制限",
        "Share with Friends": "友達と共有",
        "Rate Us": "評価する",
        "Privacy Policy": "プライバシーポリシー",
        "Terms of Use (EULA)": "利用規約 (EULA)",
        "Image saved to photos": "写真に保存された画像",
        "Save to Photos": "写真に保存",
        "Search": "検索",
        "Share": "共有",
        "Save": "保存",
        "Watch ad": "広告を視聴",
        "CONTINUE": "続ける",
        "3 DAYS FREE": "3日間無料",
        "DISCOUNT": "割引",
        "months": "ヶ月",
        "month": "月",
        "MOST POPULAR": "最も人気",
        "then": "その後",
        "Payment successful": "支払いが成功しました",
        "You are using PREMIUM version of app now": "現在、プレミアムバージョンのアプリを使用しています",
        "Success": "成功",
        "SUCCESS": "成功",
        "ERROR": "エラー",
        "Error": "エラー",
        "You have no active subscription.": "アクティブなサブスクリプションはありません",
        "Buy Premium": "プレミアムを購入",
        "Restore Purchases": "購入の復元",
        "You are using the premium version of this app.":
            "このアプリのプレミアムバージョンを使用しています"
      },
      "ar": {
        "Settings": "الإعدادات",
        "Remove Limits": "إزالة الحدود",
        "Check out this amazing app at": "تحقق من هذا التطبيق المذهل على",
        "Remaining": "المتبقي",
        "Daily Limit": "الحد اليومي",
        "Share with Friends": "مشاركة مع الأصدقاء",
        "Rate Us": "قيمنا",
        "Privacy Policy": "سياسة الخصوصية",
        "Terms of Use (EULA)": "شروط الاستخدام (EULA)",
        "Image saved to photos": "الصورة المحفوظة في الصور",
        "Save to Photos": "حفظ في الصور",
        "Search": "بحث",
        "Share": "مشاركة",
        "Save": "حفظ",
        "Watch ad": "مشاهدة الإعلان",
        "CONTINUE": "متابعة",
        "3 DAYS FREE": "3 أيام مجاناً",
        "DISCOUNT": "خصم",
        "months": "شهور",
        "month": "شهر",
        "MOST POPULAR": "الأكثر شيوعًا",
        "then": "ثم",
        "Payment successful": "تم الدفع بنجاح",
        "You are using PREMIUM version of app now":
            "أنت تستخدم الآن النسخة المميزة من التطبيق",
        "Success": "نجاح",
        "SUCCESS": "نجاح",
        "ERROR": "خطأ",
        "Error": "خطأ",
        "You have no active subscription.": "ليس لديك اشتراك نشط.",
        "Buy Premium": "شراء المميز",
        "Restore Purchases": "استعادة المشتريات",
        "You are using the premium version of this app.":
            "أنت تستخدم النسخة المميزة من هذا التطبيق."
      },
      "ru": {
        "Settings": "Настройки",
        "Remove Limits": "Убрать ограничения",
        "Check out this amazing app at":
            "Ознакомьтесь с этим удивительным приложением на",
        "Remaining": "Осталось",
        "Daily Limit": "Дневное ограничение",
        "Share with Friends": "Поделиться с друзьями",
        "Rate Us": "Оцените нас",
        "Privacy Policy": "Политика конфиденциальности",
        "Terms of Use (EULA)": "Условия использования (EULA)",
        "Image saved to photos": "Изображение сохранено в фото",
        "Save to Photos": "Сохранить в фото",
        "Search": "Поиск",
        "Share": "Поделиться",
        "Save": "Сохранить",
        "Watch ad": "Посмотреть рекламу",
        "CONTINUE": "ПРОДОЛЖИТЬ",
        "3 DAYS FREE": "3 ДНЯ БЕСПЛАТНО",
        "DISCOUNT": "СКИДКА",
        "months": "месяцы",
        "month": "месяц",
        "MOST POPULAR": "САМОЕ ПОПУЛЯРНОЕ",
        "then": "затем",
        "Payment successful": "Платеж успешен",
        "You are using PREMIUM version of app now":
            "Вы используете ПРЕМИУМ-версию приложения",
        "Success": "Успех",
        "SUCCESS": "УСПЕХ",
        "ERROR": "ОШИБКА",
        "Error": "Ошибка",
        "You have no active subscription.": "У вас нет активной подписки.",
        "Buy Premium": "Купить Премиум",
        "Restore Purchases": "Восстановить покупки",
        "You are using the premium version of this app.":
            "Вы используете премиум-версию этого приложения."
      },
      "zh": {
        "Settings": "设置",
        "Remove Limits": "移除限制",
        "Check out this amazing app at": "请查看这个令人惊叹的应用程序",
        "Remaining": "剩余",
        "Daily Limit": "每日限额",
        "Share with Friends": "与朋友分享",
        "Rate Us": "给我们评分",
        "Privacy Policy": "隐私政策",
        "Terms of Use (EULA)": "使用条款（EULA）",
        "Image saved to photos": "图像已保存到照片",
        "Save to Photos": "保存到照片",
        "Search": "搜索",
        "Share": "分享",
        "Save": "保存",
        "Watch ad": "观看广告",
        "CONTINUE": "继续",
        "3 DAYS FREE": "3天免费",
        "DISCOUNT": "折扣",
        "months": "月",
        "month": "月",
        "MOST POPULAR": "最受欢迎",
        "then": "然后",
        "Payment successful": "支付成功",
        "You are using PREMIUM version of app now": "您现在正在使用高级版本的应用程序",
        "Success": "成功",
        "SUCCESS": "成功",
        "ERROR": "错误",
        "Error": "错误",
        "You have no active subscription.": "您没有活跃的订阅。",
        "Buy Premium": "购买高级版",
        "Restore Purchases": "恢复购买",
        "You are using the premium version of this app.": "您正在使用此应用程序的高级版。"
      },
      "pt": {
        "Settings": "Configurações",
        "Remove Limits": "Remover Limites",
        "Check out this amazing app at": "Confira este incrível aplicativo em",
        "Remaining": "Restante",
        "Daily Limit": "Limite Diário",
        "Share with Friends": "Compartilhar com Amigos",
        "Rate Us": "Avalie-nos",
        "Privacy Policy": "Política de Privacidade",
        "Terms of Use (EULA)": "Termos de Uso (EULA)",
        "Image saved to photos": "Imagem salva nas fotos",
        "Save to Photos": "Salvar nas Fotos",
        "Search": "Buscar",
        "Share": "Compartilhar",
        "Save": "Salvar",
        "Watch ad": "Assistir anúncio",
        "CONTINUE": "CONTINUAR",
        "3 DAYS FREE": "3 DIAS GRÁTIS",
        "DISCOUNT": "DESCONTO",
        "months": "meses",
        "month": "mês",
        "MOST POPULAR": "MAIS POPULAR",
        "then": "então",
        "Payment successful": "Pagamento bem-sucedido",
        "You are using PREMIUM version of app now":
            "Você está usando a versão PREMIUM deste aplicativo agora",
        "Success": "Sucesso",
        "SUCCESS": "SUCESSO",
        "ERROR": "ERRO",
        "Error": "Erro",
        "You have no active subscription.":
            "Você não possui uma assinatura ativa.",
        "Buy Premium": "Comprar Premium",
        "Restore Purchases": "Restaurar Compras",
        "You are using the premium version of this app.":
            "Você está usando a versão premium deste aplicativo."
      },
      "hi": {
        "Settings": "सेटिंग्स",
        "Remove Limits": "सीमाएँ हटाएं",
        "Check out this amazing app at": "इस शानदार ऐप की जांच करें",
        "Remaining": "शेष",
        "Daily Limit": "दैनिक सीमा",
        "Share with Friends": "मित्रों के साथ साझा करें",
        "Rate Us": "हमें रेटिंग दें",
        "Privacy Policy": "गोपनीयता नीति",
        "Terms of Use (EULA)": "उपयोग की शर्तें (EULA)",
        "Image saved to photos": "तस्वीर फ़ोटो में सहेजी गई",
        "Save to Photos": "फ़ोटो में सहेजें",
        "Search": "खोजें",
        "Share": "साझा करें",
        "Save": "सहेजें",
        "Watch ad": "विज्ञापन देखें",
        "CONTINUE": "जारी रखें",
        "3 DAYS FREE": "3 दिन नि:शुल्क",
        "DISCOUNT": "छूट",
        "months": "महीने",
        "month": "महीना",
        "MOST POPULAR": "सबसे लोकप्रिय",
        "then": "तब",
        "Payment successful": "भुगतान सफल",
        "You are using PREMIUM version of app now":
            "आप अब ऐप का प्रीमियम संस्करण उपयोग कर रहे हैं",
        "Success": "सफलता",
        "SUCCESS": "सफलता",
        "ERROR": "त्रुटि",
        "Error": "त्रुटि",
        "You have no active subscription.": "आपका कोई सक्रिय सदस्यता नहीं है।",
        "Buy Premium": "प्रीमियम खरीदें",
        "Restore Purchases": "खरीदारी को बहाल करें",
        "You are using the premium version of this app.":
            "आप इस ऐप का प्रीमियम संस्करण उपयोग कर रहे हैं।"
      },
      "ms": {
        "Settings": "Tetapan",
        "Remove Limits": "Alihkan Had",
        "Check out this amazing app at": "Lihat aplikasi menakjubkan ini di",
        "Remaining": "Baki",
        "Daily Limit": "Had Harian",
        "Share with Friends": "Kongsi dengan Rakan",
        "Rate Us": "Beri Kadar Kami",
        "Privacy Policy": "Dasar Privasi",
        "Terms of Use (EULA)": "Terma Penggunaan (EULA)",
        "Image saved to photos": "Gambar disimpan dalam foto",
        "Save to Photos": "Simpan dalam Foto",
        "Search": "Cari",
        "Share": "Kongsi",
        "Save": "Simpan",
        "Watch ad": "Tonton iklan",
        "CONTINUE": "TERUSKAN",
        "3 DAYS FREE": "3 HARI PERCUMA",
        "DISCOUNT": "DISKAUN",
        "months": "bulan",
        "month": "bulan",
        "MOST POPULAR": "PALING POPULAR",
        "then": "kemudian",
        "Payment successful": "Pembayaran berjaya",
        "You are using PREMIUM version of app now":
            "Anda kini menggunakan versi PREMIUM aplikasi ini",
        "Success": "Berjaya",
        "SUCCESS": "BERJAYA",
        "ERROR": "RALAT",
        "Error": "Ralat",
        "You have no active subscription.":
            "Anda tidak mempunyai langganan aktif.",
        "Buy Premium": "Beli Premium",
        "Restore Purchases": "Pulihkan Pembelian",
        "You are using the premium version of this app.":
            "Anda menggunakan versi premium aplikasi ini."
      },
      "ko": {
        "Settings": "설정",
        "Remove Limits": "제한 해제",
        "Check out this amazing app at": "이 멋진 앱을 확인하세요",
        "Remaining": "남은",
        "Daily Limit": "일일 한도",
        "Share with Friends": "친구들과 공유하기",
        "Rate Us": "평가하기",
        "Privacy Policy": "개인정보 처리방침",
        "Terms of Use (EULA)": "이용약관 (EULA)",
        "Image saved to photos": "사진에 저장된 이미지",
        "Save to Photos": "사진에 저장하기",
        "Search": "검색",
        "Share": "공유",
        "Save": "저장",
        "Watch ad": "광고 시청",
        "CONTINUE": "계속",
        "3 DAYS FREE": "3일 무료",
        "DISCOUNT": "할인",
        "months": "개월",
        "month": "개월",
        "MOST POPULAR": "가장 인기 있는",
        "then": "그런 다음",
        "Payment successful": "결제 성공",
        "You are using PREMIUM version of app now":
            "당신은 현재 프리미엄 버전의 앱을 사용 중입니다",
        "Success": "성공",
        "SUCCESS": "성공",
        "ERROR": "오류",
        "Error": "오류",
        "You have no active subscription.": "활성 구독이 없습니다.",
        "Buy Premium": "프리미엄 구매",
        "Restore Purchases": "구매 복원",
        "You are using the premium version of this app.":
            "당신은 이 앱의 프리미엄 버전을 사용 중입니다."
      },
      "id": {
        "Settings": "Pengaturan",
        "Remove Limits": "Hapus Batasan",
        "Check out this amazing app at": "Cek aplikasi menakjubkan ini di",
        "Remaining": "Sisa",
        "Daily Limit": "Batas Harian",
        "Share with Friends": "Bagikan dengan Teman",
        "Rate Us": "Beri Kami Nilai",
        "Privacy Policy": "Kebijakan Privasi",
        "Terms of Use (EULA)": "Syarat Penggunaan (EULA)",
        "Image saved to photos": "Gambar disimpan ke foto",
        "Save to Photos": "Simpan ke Foto",
        "Search": "Cari",
        "Share": "Bagikan",
        "Save": "Simpan",
        "Watch ad": "Tonton iklan",
        "CONTINUE": "LANJUTKAN",
        "3 DAYS FREE": "3 HARI GRATIS",
        "DISCOUNT": "DISKON",
        "months": "bulan",
        "month": "bulan",
        "MOST POPULAR": "PALING POPULER",
        "then": "kemudian",
        "Payment successful": "Pembayaran berhasil",
        "You are using PREMIUM version of app now":
            "Anda saat ini menggunakan versi PREMIUM dari aplikasi ini",
        "Success": "Berhasil",
        "SUCCESS": "BERHASIL",
        "ERROR": "KESALAHAN",
        "Error": "Kesalahan",
        "You have no active subscription.":
            "Anda tidak memiliki langganan aktif.",
        "Buy Premium": "Beli Premium",
        "Restore Purchases": "Pulihkan Pembelian",
        "You are using the premium version of this app.":
            "Anda menggunakan versi premium dari aplikasi ini."
      }
    };
  }

  static Map<String, Map<String, String>> mergeMaps(
      Map<String, Map<String, String>> map1,
      Map<String, Map<String, String>> map2) {
    Map<String, Map<String, String>> mergedMap = {};

    // Add all entries from map1
    mergedMap.addAll(map1);

    // Merge entries from map2
    map2.forEach((key, value) {
      if (mergedMap.containsKey(key)) {
        // If the key exists in both maps, merge the inner maps
        mergedMap[key]?.addAll(value);
      } else {
        // If the key doesn't exist in the merged map, add it
        mergedMap[key] = value;
      }
    });

    return mergedMap;
  }
}
