// convert to en,  tr , fr , es, de, it, ja, ar, ru, zh , pt , hi , ms , ko , id, nl
// copy paste json output. write all in one output

class TranslateHelper {
  static Map<String, Map<String, String>> getHelperTranslations() {
    return {
      "en": {
        "Support Us!": "Support Us!",
        "partof": "Be part of our growth story by giving us a rating.",
        "Weekly": "Weekly",
        "Yearly": "Yearly",
        "Settings": "Settings",
        "Remove Limits": "Remove Limits",
        "amazingapp": "Check out this amazing app at",
        "Remaining": "Remaining",
        "Daily Limit": "Daily Limit",
        "FREE": "FREE",
        "Rate": "Rate",
        "ONE TIME OFFER": "ONE TIME OFFER",
        "Share with Friends": "Share with Friends",
        "Best Value": "Best Value",
        "Rate Us": "Rate Us",
        "Submit": "Submit",
        "Loading": "Loading...",
        "1 Week": "1 Week",
        "1 Year": "1 Year",
        "month": "%s Month",
        "rate_comment": "If you like this app please rate it",
        "Lifetime": "Lifetime",
        "off": "%s% OFF",
        "Privacy": "Privacy Policy",
        "Terms": "Terms of Use",
        "saved": "Image saved to photos",
        "Download": "Download",
        "Save to Photos": "Save to Photos",
        "Search": "Search",
        "Share": "Share",
        "Save": "Save",
        "Cancel Anytime": "Cancel Anytime",
        "Premium": "Premium",
        "pr1": "Unlock Premium",
        "pr2": "Full Access",
        "pr3": "Try Premium",
        "pr4": "Try Premium Free",
        "pr5": "Unlock Unlimited Access",
        "btn1": "Continue",
        "btn2": "Start Free Trial",
        "btn3": "Start 3 Days Free Trial",
        "btn4": "Start Free Trial and Plan",
        "Watch ad": "Watch ad",
        "CONTINUE": "CONTINUE",
        "free3": "3 DAYS FREE",
        "No payment now": "No payment now",
        "then": "then",
        "Payment successful": "Payment successful",
        "premiumDesc": "You are using PREMIUM version of app now",
        "Success": "Success",
        "SUCCESS": "SUCCESS",
        "ERROR": "ERROR",
        "Error": "Error",
        "nosubs": "You have no active subscription.",
        "buyPremium": "✓ Buy Premium",
        "Buy Premium": "Buy Premium",
        "ALERT": "ALERT",
        "Restore Purchases": "Restore Purchases",
        "premiumuse": "You are using the premium version of this app."
      },
      "tr": {
        "Support Us!": "Bizi Destekleyin!",
        "partof": "Bize bir puan vererek büyüme hikayemizin bir parçası olun.",
        "Weekly": "Haftalık",
        "Yearly": "Yıllık",
        "Settings": "Ayarlar",
        "FREE": "ÜCRETSİZ",
        "Rate": "Değerlendir",
        "ONE TIME OFFER": "BİR KEREYE MAHSUS TEKLİF",
        "Remove Limits": "Sınırları Kaldır",
        "amazingapp": "Bu harika uygulamayı inceleyin",
        "Remaining": "Kalan",
        "Daily Limit": "Günlük Limit",
        "Share with Friends": "Arkadaşlarla Paylaş",
        "Rate Us": "Bizi Oyla",
        "Submit": "Gönder",
        "Loading": "Yükleniyor...",
        "1 Week": "1 Hafta",
        "1 Year": "1 Yıl",
        "month": "%s Ay",
        "rate_comment": "Bu uygulamayı beğendiyseniz lütfen oy verin",
        "Lifetime": "Ömür Boyu",
        "off": "%s% İNDİRİM",
        "Privacy": "Gizlilik Politikası",
        "Terms": "Kullanım Şartları",
        "saved": "Görsel fotoğraflara kaydedildi",
        "Download": "İndir",
        "Save to Photos": "Fotoğraflara Kaydet",
        "Search": "Ara",
        "Share": "Paylaş",
        "Save": "Kaydet",
        "Cancel Anytime": "Her Zaman İptal Et",
        "Premium": "Premium",
        "pr1": "Premium'un Kilidini Aç",
        "pr2": "Tam Erişim",
        "pr3": "Premium'u Dene",
        "pr4": "Ücretsiz Premium'u Dene",
        "pr5": "Sınırsız Erişimi Aç",
        "btn1": "Devam Et",
        "btn2": "Ücretsiz Deneme Başlat",
        "btn3": "3 Gün Ücretsiz Deneme Başlat",
        "btn4": "Ücretsiz Deneme ve Plan Başlat",
        "Watch ad": "Reklam izle",
        "CONTINUE": "DEVAM ET",
        "free3": "3 GÜN ÜCRETSİZ",
        "No payment now": "Şimdi ödeme yok",
        "then": "sonra",
        "Payment successful": "Ödeme başarılı",
        "premiumDesc": "Şimdi uygulamanın PREMIUM sürümünü kullanıyorsunuz",
        "Success": "Başarılı",
        "SUCCESS": "BAŞARILI",
        "ERROR": "HATA",
        "Error": "Hata",
        "nosubs": "Aktif aboneliğiniz yok.",
        "buyPremium": "✓ Premium Satın Al",
        "Buy Premium": "Premium Satın Al",
        "ALERT": "UYARI",
        "Restore Purchases": "Satın Alımları Geri Yükle",
        "premiumuse": "Bu uygulamanın premium sürümünü kullanıyorsunuz."
      },
      "fr": {
        "Support Us!": "Soutenez-nous!",
        "partof":
            "Faites partie de notre histoire de croissance en nous donnant une note.",
        "Weekly": "Hebdomadaire",
        "Yearly": "Annuel",
        "Settings": "Paramètres",
        "FREE": "GRATUIT",
        "Rate": "Évaluer",
        "ONE TIME OFFER": "OFFRE UNIQUE",
        "Remove Limits": "Supprimer les Limites",
        "amazingapp": "Découvrez cette application incroyable à",
        "Remaining": "Restant",
        "Daily Limit": "Limite Quotidienne",
        "Share with Friends": "Partager avec des Amis",
        "Rate Us": "Évaluez-nous",
        "Submit": "Soumettre",
        "Loading": "Chargement...",
        "1 Week": "1 Semaine",
        "1 Year": "1 An",
        "month": "%s Mois",
        "rate_comment": "Si vous aimez cette application, veuillez la noter",
        "Lifetime": "À Vie",
        "off": "%s% DE RÉDUCTION",
        "Privacy": "Politique de Confidentialité",
        "Terms": "Conditions d'Utilisation",
        "saved": "Image enregistrée dans les photos",
        "Download": "Télécharger",
        "Save to Photos": "Enregistrer dans les Photos",
        "Search": "Rechercher",
        "Share": "Partager",
        "Save": "Enregistrer",
        "Cancel Anytime": "Annuler à tout moment",
        "Premium": "Premium",
        "pr1": "Débloquer Premium",
        "pr2": "Accès Complet",
        "pr3": "Essayer Premium",
        "pr4": "Essayer Premium Gratuitement",
        "pr5": "Débloquer Accès Illimité",
        "btn1": "Continuer",
        "btn2": "Commencer l'Essai Gratuit",
        "btn3": "Commencer 3 Jours d'Essai Gratuit",
        "btn4": "Commencez l'essai gratuit et le plan",
        "Watch ad": "Regarder une publicité",
        "CONTINUE": "CONTINUER",
        "free3": "3 JOURS GRATUITS",
        "No payment now": "Aucun paiement maintenant",
        "then": "puis",
        "Payment successful": "Paiement réussi",
        "premiumDesc":
            "Vous utilisez maintenant la version PREMIUM de l'application",
        "Success": "Succès",
        "SUCCESS": "SUCCÈS",
        "ERROR": "ERREUR",
        "Error": "Erreur",
        "nosubs": "Vous n'avez aucun abonnement actif.",
        "buyPremium": "✓ Acheter Premium",
        "Buy Premium": "Acheter Premium",
        "ALERT": "ALERTE",
        "Restore Purchases": "Restaurer les Achats",
        "premiumuse": "Vous utilisez la version premium de cette application."
      },
      "es": {
        "Support Us!": "¡Apóyanos!",
        "partof":
            "Sé parte de nuestra historia de crecimiento dándonos una calificación.",
        "Weekly": "Semanal",
        "Yearly": "Anual",
        "Settings": "Configuración",
        "FREE": "GRATIS",
        "Rate": "Calificar",
        "ONE TIME OFFER": "OFERTA ÚNICA",
        "Remove Limits": "Quitar límites",
        "amazingapp": "Mira esta increíble aplicación en",
        "Remaining": "Restante",
        "Daily Limit": "Límite diario",
        "Share with Friends": "Compartir con amigos",
        "Rate Us": "Califícanos",
        "Submit": "Enviar",
        "Loading": "Cargando...",
        "1 Week": "1 Semana",
        "1 Year": "1 Año",
        "month": "%s Mes",
        "rate_comment": "Si te gusta esta aplicación, por favor califícala",
        "Lifetime": "De por vida",
        "off": "%s% DESCUENTO",
        "Privacy": "Política de privacidad",
        "Terms": "Términos de uso",
        "saved": "Imagen guardada en fotos",
        "Download": "Descargar",
        "Save to Photos": "Guardar en fotos",
        "Search": "Buscar",
        "Share": "Compartir",
        "Save": "Guardar",
        "Cancel Anytime": "Cancela en cualquier momento",
        "Premium": "Premium",
        "pr1": "Desbloquear Premium",
        "pr2": "Acceso completo",
        "pr3": "Prueba Premium",
        "pr4": "Prueba Premium gratis",
        "pr5": "Desbloquear acceso ilimitado",
        "btn1": "Continuar",
        "btn2": "Comenzar prueba gratuita",
        "btn3": "Comenzar prueba gratuita de 3 días",
        "btn4": "Iniciar prueba gratuita y plan",
        "Watch ad": "Ver anuncio",
        "CONTINUE": "CONTINUAR",
        "free3": "3 DÍAS GRATIS",
        "No payment now": "No hay pago ahora",
        "then": "entonces",
        "Payment successful": "Pago exitoso",
        "premiumDesc": "Ahora estás usando la versión PREMIUM de la aplicación",
        "Success": "Éxito",
        "SUCCESS": "ÉXITO",
        "ERROR": "ERROR",
        "Error": "Error",
        "nosubs": "No tienes ninguna suscripción activa.",
        "buyPremium": "✓ Comprar Premium",
        "Buy Premium": "Comprar Premium",
        "ALERT": "ALERTA",
        "Restore Purchases": "Restaurar compras",
        "premiumuse": "Estás usando la versión premium de esta aplicación."
      },
      "de": {
        "Support Us!": "Unterstützen Sie uns!",
        "partof":
            "Werden Sie Teil unserer Erfolgsgeschichte, indem Sie uns eine Bewertung geben.",
        "Weekly": "Wöchentlich",
        "Yearly": "Jährlich",
        "Settings": "Einstellungen",
        "FREE": "KOSTENLOS",
        "Rate": "Bewerten",
        "ONE TIME OFFER": "EINMALIGES ANGEBOT",
        "Remove Limits": "Grenzen entfernen",
        "amazingapp": "Schau dir diese tolle App an bei",
        "Remaining": "Verbleibend",
        "Daily Limit": "Tägliches Limit",
        "Share with Friends": "Mit Freunden teilen",
        "Rate Us": "Bewerte uns",
        "Submit": "Einreichen",
        "Loading": "Laden...",
        "1 Week": "1 Woche",
        "1 Year": "1 Jahr",
        "month": "%s Monat",
        "rate_comment": "Wenn dir diese App gefällt, bitte bewerte sie",
        "Lifetime": "Lebenslang",
        "off": "%s% RABATT",
        "Privacy": "Datenschutz-Bestimmungen",
        "Terms": "Nutzungsbedingungen",
        "saved": "Bild in Fotos gespeichert",
        "Download": "Herunterladen",
        "Save to Photos": "In Fotos speichern",
        "Search": "Suchen",
        "Share": "Teilen",
        "Save": "Speichern",
        "Cancel Anytime": "Jederzeit kündigen",
        "Premium": "Premium",
        "pr1": "Premium freischalten",
        "pr2": "Vollzugriff",
        "pr3": "Premium ausprobieren",
        "pr4": "Premium gratis ausprobieren",
        "pr5": "Unbegrenzten Zugang freischalten",
        "btn1": "Weiter",
        "btn2": "Kostenlose Testversion starten",
        "btn3": "3 Tage kostenlose Testversion starten",
        "btn4": "Kostenlose Testversion und Plan starten",
        "Watch ad": "Anzeige ansehen",
        "CONTINUE": "WEITER",
        "free3": "3 TAGE GRATIS",
        "No payment now": "Kein Zahlung jetzt",
        "then": "dann",
        "Payment successful": "Zahlung erfolgreich",
        "premiumDesc": "Du verwendest jetzt die PREMIUM-Version der App",
        "Success": "Erfolg",
        "SUCCESS": "ERFOLG",
        "ERROR": "FEHLER",
        "Error": "Fehler",
        "nosubs": "Du hast kein aktives Abonnement.",
        "buyPremium": "✓ Premium kaufen",
        "Buy Premium": "Premium kaufen",
        "ALERT": "ALARM",
        "Restore Purchases": "Käufe wiederherstellen",
        "premiumuse": "Du verwendest die Premium-Version dieser App."
      },
      "it": {
        "Support Us!": "Sosteneteci!",
        "partof":
            "Fai parte della nostra storia di crescita dandoci una valutazione.",
        "Weekly": "Settimanale",
        "Yearly": "Annuale",
        "Settings": "Impostazioni",
        "Remove Limits": "Rimuovi limiti",
        "amazingapp": "Scopri questa fantastica app su",
        "Remaining": "Rimanente",
        "Daily Limit": "Limite giornaliero",
        "Share with Friends": "Condividi con amici",
        "FREE": "GRATUITO",
        "Rate": "Valuta",
        "ONE TIME OFFER": "OFFERTA UNICA",
        "Rate Us": "Valutaci",
        "Submit": "Invia",
        "Loading": "Caricamento...",
        "1 Week": "1 Settimana",
        "1 Year": "1 Anno",
        "month": "%s Mese",
        "rate_comment": "Se ti piace questa app, per favore valutala",
        "Lifetime": "A vita",
        "off": "%s% DI SCONTO",
        "Privacy": "Informativa sulla privacy",
        "Terms": "Termini di utilizzo",
        "saved": "Immagine salvata nelle foto",
        "Download": "Scarica",
        "Save to Photos": "Salva nelle foto",
        "Search": "Cerca",
        "Share": "Condividi",
        "Save": "Salva",
        "Cancel Anytime": "Annulla in qualsiasi momento",
        "Premium": "Premium",
        "pr1": "Sblocca Premium",
        "pr2": "Accesso completo",
        "pr3": "Prova Premium",
        "pr4": "Prova Premium gratis",
        "pr5": "Sblocca accesso illimitato",
        "btn1": "Continua",
        "btn2": "Inizia prova gratuita",
        "btn3": "Inizia prova gratuita di 3 giorni",
        "btn4": "Inizia prova gratuita e piano",
        "Watch ad": "Guarda annuncio",
        "CONTINUE": "CONTINUA",
        "free3": "3 GIORNI GRATIS",
        "No payment now": "Nessun pagamento ora",
        "then": "poi",
        "Payment successful": "Pagamento riuscito",
        "premiumDesc": "Ora stai usando la versione PREMIUM dell'app",
        "Success": "Successo",
        "SUCCESS": "SUCCESSO",
        "ERROR": "ERRORE",
        "Error": "Errore",
        "nosubs": "Non hai nessun abbonamento attivo.",
        "buyPremium": "✓ Acquista Premium",
        "Buy Premium": "Acquista Premium",
        "ALERT": "ALLERTA",
        "Restore Purchases": "Ripristina acquisti",
        "premiumuse": "Stai usando la versione premium di questa app."
      },
      "ja": {
        "Support Us!": "サポートしてください！",
        "partof": "私たちに評価を与えることで、成長ストーリーの一部になりましょう。",
        "Weekly": "毎週",
        "Yearly": "毎年",
        "FREE": "無料",
        "Rate": "評価する",
        "ONE TIME OFFER": "一度限りのオファー",
        "Settings": "設定",
        "Remove Limits": "制限を解除",
        "amazingapp": "この素晴らしいアプリをチェックしてください",
        "Remaining": "残り",
        "Daily Limit": "日次制限",
        "Share with Friends": "友達と共有",
        "Rate Us": "評価する",
        "Submit": "提出する",
        "Loading": "読み込み中...",
        "1 Week": "1週間",
        "1 Year": "1年",
        "month": "%sか月",
        "rate_comment": "このアプリが気に入ったら評価してください",
        "Lifetime": "生涯",
        "off": "%s%オフ",
        "Privacy": "プライバシーポリシー",
        "Terms": "利用規約",
        "saved": "写真に保存されました",
        "Download": "ダウンロード",
        "Save to Photos": "写真に保存",
        "Search": "検索",
        "Share": "共有",
        "Save": "保存",
        "Cancel Anytime": "いつでもキャンセル",
        "Premium": "プレミアム",
        "pr1": "プレミアムを解除",
        "pr2": "フルアクセス",
        "pr3": "プレミアムを試す",
        "pr4": "プレミアムを無料で試す",
        "pr5": "無制限アクセスを解除",
        "btn1": "続行",
        "btn2": "無料トライアルを開始",
        "btn3": "3日間無料トライアルを開始",
        "btn4": "無料トライアルとプランを開始",
        "Watch ad": "広告を見る",
        "CONTINUE": "続行",
        "free3": "3日間無料",
        "No payment now": "今は支払いなし",
        "then": "その後",
        "Payment successful": "支払い成功",
        "premiumDesc": "あなたは現在プレミアムバージョンのアプリを使用しています",
        "Success": "成功",
        "SUCCESS": "成功",
        "ERROR": "エラー",
        "Error": "エラー",
        "nosubs": "有効なサブスクリプションがありません。",
        "buyPremium": "✓ プレミアムを購入",
        "Buy Premium": "プレミアムを購入",
        "ALERT": "警告",
        "Restore Purchases": "購入を復元",
        "premiumuse": "現在プレミアムバージョンのアプリを使用しています。"
      },
      "ar": {
        "Support Us!": "ادعمنا!",
        "partof": "كن جزءًا من قصة نمونا من خلال إعطائنا تقييمًا.",
        "Weekly": "أسبوعي",
        "Yearly": "سنوي",
        "Settings": "الإعدادات",
        "FREE": "مجاني",
        "Rate": "قيم",
        "ONE TIME OFFER": "عرض لمرة واحدة",
        "Remove Limits": "إزالة القيود",
        "amazingapp": "تحقق من هذا التطبيق الرائع في",
        "Remaining": "المتبقي",
        "Daily Limit": "الحد اليومي",
        "Share with Friends": "شارك مع الأصدقاء",
        "Rate Us": "قيمنا",
        "Submit": "إرسال",
        "Loading": "جارٍ التحميل...",
        "1 Week": "1 أسبوع",
        "1 Year": "1 سنة",
        "month": "%s شهر",
        "rate_comment": "إذا أعجبك هذا التطبيق يرجى تقييمه",
        "Lifetime": "مدى الحياة",
        "off": "%s٪ خصم",
        "Privacy": "سياسة الخصوصية",
        "Terms": "شروط الاستخدام",
        "saved": "تم حفظ الصورة في الصور",
        "Download": "تنزيل",
        "Save to Photos": "حفظ في الصور",
        "Search": "بحث",
        "Share": "مشاركة",
        "Save": "حفظ",
        "Cancel Anytime": "إلغاء في أي وقت",
        "Premium": "ممتاز",
        "pr1": "فتح المميزات",
        "pr2": "وصول كامل",
        "pr3": "جرب المميزات",
        "pr4": "جرب المميزات مجاناً",
        "pr5": "فتح الوصول غير المحدود",
        "btn1": "استمر",
        "btn2": "ابدأ التجربة المجانية",
        "btn3": "ابدأ التجربة المجانية لمدة 3 أيام",
        "btn4": "ابدأ التجربة المجانية والخطة",
        "Watch ad": "شاهد الإعلان",
        "CONTINUE": "استمر",
        "free3": "3 أيام مجاناً",
        "No payment now": "لا توجد دفعة الآن",
        "then": "ثم",
        "Payment successful": "تم الدفع بنجاح",
        "premiumDesc": "أنت تستخدم الآن الإصدار المتميز من التطبيق",
        "Success": "نجاح",
        "SUCCESS": "نجاح",
        "ERROR": "خطأ",
        "Error": "خطأ",
        "nosubs": "ليس لديك أي اشتراك نشط.",
        "buyPremium": "✓ شراء المميزات",
        "Buy Premium": "شراء المميزات",
        "ALERT": "تحذير",
        "Restore Purchases": "استعادة المشتريات",
        "premiumuse": "أنت تستخدم الإصدار المتميز من هذا التطبيق."
      },
      "ru": {
        "Support Us!": "Поддержите нас!",
        "partof": "Станьте частью нашей истории роста, оценив нас.",
        "Weekly": "Еженедельно",
        "Yearly": "Ежегодно",
        "Settings": "Настройки",
        "Remove Limits": "Снять ограничения",
        "amazingapp": "Посмотрите это удивительное приложение на",
        "Remaining": "Оставшийся",
        "Daily Limit": "Ежедневный лимит",
        "Share with Friends": "Поделиться с друзьями",
        "Rate Us": "Оцените нас",
        "Submit": "Отправить",
        "Loading": "Загрузка...",
        "FREE": "БЕСПЛАТНО",
        "Rate": "Оценить",
        "ONE TIME OFFER": "ОДНОРАЗОВОЕ ПРЕДЛОЖЕНИЕ",
        "1 Week": "1 неделя",
        "1 Year": "1 год",
        "month": "%s месяц",
        "rate_comment":
            "Если вам нравится это приложение, пожалуйста, оцените его",
        "Lifetime": "Пожизненный",
        "off": "%s% скидка",
        "Privacy": "Политика конфиденциальности",
        "Terms": "Условия использования",
        "saved": "Изображение сохранено в фото",
        "Download": "Скачать",
        "Save to Photos": "Сохранить в фото",
        "Search": "Поиск",
        "Share": "Поделиться",
        "Save": "Сохранить",
        "Cancel Anytime": "Отмена в любое время",
        "Premium": "Премиум",
        "pr1": "Разблокировать премиум",
        "pr2": "Полный доступ",
        "pr3": "Попробовать премиум",
        "pr4": "Попробовать премиум бесплатно",
        "pr5": "Разблокировать неограниченный доступ",
        "btn1": "Продолжить",
        "btn2": "Начать бесплатную пробную версию",
        "btn3": "Начать 3-дневную бесплатную пробную версию",
        "btn4": "Начать бесплатную пробную версию и план",
        "Watch ad": "Смотреть рекламу",
        "CONTINUE": "ПРОДОЛЖИТЬ",
        "free3": "3 ДНЯ БЕСПЛАТНО",
        "No payment now": "Без оплаты сейчас",
        "then": "затем",
        "Payment successful": "Платеж прошел успешно",
        "premiumDesc": "Теперь вы используете ПРЕМИУМ-версию приложения",
        "Success": "Успех",
        "SUCCESS": "УСПЕХ",
        "ERROR": "ОШИБКА",
        "Error": "Ошибка",
        "nosubs": "У вас нет активной подписки.",
        "buyPremium": "✓ Купить премиум",
        "Buy Premium": "Купить премиум",
        "ALERT": "ВНИМАНИЕ",
        "Restore Purchases": "Восстановить покупки",
        "premiumuse": "Вы используете премиум-версию этого приложения."
      },
      "zh": {
        "Support Us!": "支持我们！",
        "partof": "通过给我们评分，成为我们成长故事的一部分。",
        "Weekly": "每周",
        "Yearly": "每年",
        "FREE": "免费",
        "Rate": "评价",
        "ONE TIME OFFER": "一次性优惠",
        "Settings": "设置",
        "Remove Limits": "移除限制",
        "amazingapp": "看看这个惊人的应用程序",
        "Remaining": "剩余",
        "Daily Limit": "每日限制",
        "Share with Friends": "与朋友分享",
        "Rate Us": "评价我们",
        "Submit": "提交",
        "Loading": "加载中...",
        "1 Week": "1 周",
        "1 Year": "1 年",
        "month": "%s 个月",
        "rate_comment": "如果你喜欢这个应用程序，请给它评分",
        "Lifetime": "终身",
        "off": "%s% 折扣",
        "Privacy": "隐私政策",
        "Terms": "使用条款",
        "saved": "图片已保存到照片",
        "Download": "下载",
        "Save to Photos": "保存到照片",
        "Search": "搜索",
        "Share": "分享",
        "Save": "保存",
        "Cancel Anytime": "随时取消",
        "Premium": "高级",
        "pr1": "解锁高级版",
        "pr2": "完全访问",
        "pr3": "尝试高级版",
        "pr4": "免费尝试高级版",
        "pr5": "解锁无限访问",
        "btn1": "继续",
        "btn2": "开始免费试用",
        "btn3": "开始3天免费试用",
        "btn4": "开始免费试用和计划",
        "Watch ad": "观看广告",
        "CONTINUE": "继续",
        "free3": "3天免费",
        "No payment now": "现在无需付款",
        "then": "然后",
        "Payment successful": "付款成功",
        "premiumDesc": "您现在正在使用高级版应用程序",
        "Success": "成功",
        "SUCCESS": "成功",
        "ERROR": "错误",
        "Error": "错误",
        "nosubs": "您没有活跃的订阅。",
        "buyPremium": "✓ 购买高级版",
        "Buy Premium": "购买高级版",
        "ALERT": "警报",
        "Restore Purchases": "恢复购买",
        "premiumuse": "您正在使用此应用程序的高级版。"
      },
      "pt": {
        "Support Us!": "Apoie-nos!",
        "partof":
            "Faça parte da nossa história de crescimento dando-nos uma classificação.",
        "Weekly": "Semanalmente",
        "FREE": "GRÁTIS",
        "Rate": "Avaliar",
        "ONE TIME OFFER": "OFERTA ÚNICA",
        "Yearly": "Anualmente",
        "Settings": "Configurações",
        "Remove Limits": "Remover Limites",
        "amazingapp": "Confira este aplicativo incrível em",
        "Remaining": "Restante",
        "Daily Limit": "Limite Diário",
        "Share with Friends": "Compartilhar com Amigos",
        "Rate Us": "Avalie-nos",
        "Submit": "Enviar",
        "Loading": "Carregando...",
        "1 Week": "1 Semana",
        "1 Year": "1 Ano",
        "month": "%s Mês",
        "rate_comment": "Se você gosta deste aplicativo, por favor, avalie-o",
        "Lifetime": "Vitalício",
        "off": "%s% DESCONTO",
        "Privacy": "Política de Privacidade",
        "Terms": "Termos de Uso",
        "saved": "Imagem salva nas fotos",
        "Download": "Baixar",
        "Save to Photos": "Salvar nas Fotos",
        "Search": "Pesquisar",
        "Share": "Compartilhar",
        "Save": "Salvar",
        "Cancel Anytime": "Cancelar a qualquer momento",
        "Premium": "Premium",
        "pr1": "Desbloquear Premium",
        "pr2": "Acesso Completo",
        "pr3": "Experimentar Premium",
        "pr4": "Experimentar Premium Gratuito",
        "pr5": "Desbloquear Acesso Ilimitado",
        "btn1": "Continuar",
        "btn2": "Iniciar Teste Gratuito",
        "btn3": "Iniciar 3 Dias de Teste Gratuito",
        "btn4": "Iniciar avaliação gratuita e plano",
        "Watch ad": "Assistir anúncio",
        "CONTINUE": "CONTINUAR",
        "free3": "3 DIAS GRATUITOS",
        "No payment now": "Sem pagamento agora",
        "then": "então",
        "Payment successful": "Pagamento bem-sucedido",
        "premiumDesc": "Você está usando a versão PREMIUM do aplicativo agora",
        "Success": "Sucesso",
        "SUCCESS": "SUCESSO",
        "ERROR": "ERRO",
        "Error": "Erro",
        "nosubs": "Você não tem nenhuma assinatura ativa.",
        "buyPremium": "✓ Comprar Premium",
        "Buy Premium": "Comprar Premium",
        "ALERT": "ALERTA",
        "Restore Purchases": "Restaurar Compras",
        "premiumuse": "Você está usando a versão premium deste aplicativo."
      },
      "hi": {
        "Support Us!": "हमें समर्थन दें!",
        "partof": "हमें रेटिंग देकर हमारी विकास कहानी का हिस्सा बनें।",
        "Weekly": "साप्ताहिक",
        "Yearly": "वार्षिक",
        "Settings": "सेटिंग्स",
        "Remove Limits": "सीमाएँ हटाएँ",
        "FREE": "मुफ़्त",
        "Rate": "दर",
        "ONE TIME OFFER": "एक बार की पेशकश",
        "amazingapp": "इस अद्भुत ऐप को देखें",
        "Remaining": "शेष",
        "Daily Limit": "दैनिक सीमा",
        "Share with Friends": "दोस्तों के साथ साझा करें",
        "Rate Us": "हमें रेट करें",
        "Submit": "प्रस्तुत करें",
        "Loading": "लोड हो रहा है...",
        "1 Week": "1 सप्ताह",
        "1 Year": "1 वर्ष",
        "month": "%s माह",
        "rate_comment": "यदि आपको यह ऐप पसंद है तो कृपया इसे रेट करें",
        "Lifetime": "जीवनकाल",
        "off": "%s% छूट",
        "Privacy": "गोपनीयता नीति",
        "Terms": "उपयोग की शर्तें",
        "saved": "छवि फोटो में सहेजी गई",
        "Download": "डाउनलोड करें",
        "Save to Photos": "फोटो में सहेजें",
        "Search": "खोज",
        "Share": "साझा करें",
        "Save": "सहेजें",
        "Cancel Anytime": "कभी भी रद्द करें",
        "Premium": "प्रीमियम",
        "pr1": "प्रीमियम अनलॉक करें",
        "pr2": "पूर्ण एक्सेस",
        "pr3": "प्रीमियम आज़माएं",
        "pr4": "प्रीमियम मुफ्त आज़माएं",
        "pr5": "अनलिमिटेड एक्सेस अनलॉक करें",
        "btn1": "जारी रखें",
        "btn2": "मुफ्त परीक्षण प्रारंभ करें",
        "btn3": "3 दिनों का मुफ्त परीक्षण प्रारंभ करें",
        "btn4": "मुफ़्त परीक्षण और योजना शुरू करें",
        "Watch ad": "विज्ञापन देखें",
        "CONTINUE": "जारी रखें",
        "free3": "3 दिन मुफ्त",
        "No payment now": "अभी कोई भुगतान नहीं",
        "then": "फिर",
        "Payment successful": "भुगतान सफल",
        "premiumDesc": "आप अब ऐप के प्रीमियम संस्करण का उपयोग कर रहे हैं",
        "Success": "सफलता",
        "SUCCESS": "सफलता",
        "ERROR": "त्रुटि",
        "Error": "त्रुटि",
        "nosubs": "आपके पास कोई सक्रिय सदस्यता नहीं है।",
        "buyPremium": "✓ प्रीमियम खरीदें",
        "Buy Premium": "प्रीमियम खरीदें",
        "ALERT": "चेतावनी",
        "Restore Purchases": "खरीदारी पुनर्स्थापित करें",
        "premiumuse": "आप इस ऐप के प्रीमियम संस्करण का उपयोग कर रहे हैं।"
      },
      "ms": {
        "Support Us!": "Sokong Kami!",
        "partof":
            "Jadilah sebahagian daripada kisah pertumbuhan kami dengan memberi kami penilaian.",
        "Weekly": "Mingguan",
        "Yearly": "Tahunan",
        "Settings": "Tetapan",
        "Remove Limits": "Alih Had",
        "FREE": "PERCUMA",
        "Rate": "Nilai",
        "ONE TIME OFFER": "TAWARAN SEKALI SAHAJA",
        "amazingapp": "Lihat aplikasi hebat ini di",
        "Remaining": "Baki",
        "Daily Limit": "Had Harian",
        "Share with Friends": "Kongsi dengan Kawan",
        "Rate Us": "Nilai Kami",
        "Submit": "Hantar",
        "Loading": "Memuat...",
        "1 Week": "1 Minggu",
        "1 Year": "1 Tahun",
        "month": "%s Bulan",
        "rate_comment": "Jika anda suka aplikasi ini sila nilaikannya",
        "Lifetime": "Seumur Hidup",
        "off": "%s% DISKAUN",
        "Privacy": "Dasar Privasi",
        "Terms": "Terma Penggunaan",
        "saved": "Imej disimpan ke foto",
        "Download": "Muat Turun",
        "Save to Photos": "Simpan ke Foto",
        "Search": "Cari",
        "Share": "Kongsi",
        "Save": "Simpan",
        "Cancel Anytime": "Batalkan Bila-bila Masa",
        "Premium": "Premium",
        "pr1": "Buka Premium",
        "pr2": "Akses Penuh",
        "pr3": "Cuba Premium",
        "pr4": "Cuba Premium Percuma",
        "pr5": "Buka Akses Tanpa Had",
        "btn1": "Teruskan",
        "btn2": "Mulakan Percubaan Percuma",
        "btn3": "Mulakan Percubaan Percuma 3 Hari",
        "btn4": "Mulakan Percubaan Percuma dan Pelan",
        "Watch ad": "Tonton iklan",
        "CONTINUE": "TERUSKAN",
        "free3": "3 HARI PERCUMA",
        "No payment now": "Tiada pembayaran sekarang",
        "then": "kemudian",
        "Payment successful": "Pembayaran berjaya",
        "premiumDesc":
            "Anda sedang menggunakan versi PREMIUM aplikasi sekarang",
        "Success": "Berjaya",
        "SUCCESS": "BERJAYA",
        "ERROR": "RALAT",
        "Error": "Ralat",
        "nosubs": "Anda tiada langganan aktif.",
        "buyPremium": "✓ Beli Premium",
        "Buy Premium": "Beli Premium",
        "ALERT": "AMARAN",
        "Restore Purchases": "Pulihkan Pembelian",
        "premiumuse": "Anda sedang menggunakan versi premium aplikasi ini."
      },
      "ko": {
        "Support Us!": "저희를 도와주세요!",
        "partof": "저희에게 평점을 주어 성장 스토리의 일부가 되세요.",
        "Weekly": "주간",
        "Yearly": "연간",
        "Settings": "설정",
        "Remove Limits": "제한 제거",
        "FREE": "무료",
        "Rate": "평가",
        "ONE TIME OFFER": "일회성 제공",
        "amazingapp": "이 놀라운 앱을 확인하세요",
        "Remaining": "남은",
        "Daily Limit": "일일 한도",
        "Share with Friends": "친구와 공유",
        "Rate Us": "평가하기",
        "Submit": "제출",
        "Loading": "로딩 중...",
        "1 Week": "1주",
        "1 Year": "1년",
        "month": "%s개월",
        "rate_comment": "이 앱이 마음에 드시면 평가해주세요",
        "Lifetime": "평생",
        "off": "%s% 할인",
        "Privacy": "개인정보 보호정책",
        "Terms": "이용 약관",
        "saved": "이미지가 사진에 저장되었습니다",
        "Download": "다운로드",
        "Save to Photos": "사진에 저장",
        "Search": "검색",
        "Share": "공유",
        "Save": "저장",
        "Cancel Anytime": "언제든지 취소",
        "Premium": "프리미엄",
        "pr1": "프리미엄 잠금 해제",
        "pr2": "전체 액세스",
        "pr3": "프리미엄 체험",
        "pr4": "프리미엄 무료 체험",
        "pr5": "무제한 액세스 잠금 해제",
        "btn1": "계속",
        "btn2": "무료 평가판 시작",
        "btn3": "3일 무료 평가판 시작",
        "btn4": "무료 체험 및 계획 시작",
        "Watch ad": "광고 보기",
        "CONTINUE": "계속",
        "free3": "3일 무료",
        "No payment now": "지금 결제 없음",
        "then": "그 다음에",
        "Payment successful": "결제 성공",
        "premiumDesc": "지금 프리미엄 버전 앱을 사용 중입니다",
        "Success": "성공",
        "SUCCESS": "성공",
        "ERROR": "오류",
        "Error": "오류",
        "nosubs": "활성 구독이 없습니다.",
        "buyPremium": "✓ 프리미엄 구매",
        "Buy Premium": "프리미엄 구매",
        "ALERT": "경고",
        "Restore Purchases": "구매 복원",
        "premiumuse": "프리미엄 버전 앱을 사용 중입니다."
      },
      "id": {
        "Support Us!": "Dukung Kami!",
        "partof":
            "Jadilah bagian dari cerita pertumbuhan kami dengan memberikan kami penilaian.",
        "Weekly": "Mingguan",
        "Yearly": "Tahunan",
        "Settings": "Pengaturan",
        "Remove Limits": "Hapus Batasan",
        "amazingapp": "Lihat aplikasi luar biasa ini di",
        "Remaining": "Tersisa",
        "Daily Limit": "Batas Harian",
        "Share with Friends": "Bagikan dengan Teman",
        "Rate Us": "Beri Penilaian",
        "Submit": "Kirim",
        "Loading": "Memuat...",
        "FREE": "GRATIS",
        "Rate": "Nilai",
        "ONE TIME OFFER": "PENAWARAN SATU KALI",
        "1 Week": "1 Minggu",
        "1 Year": "1 Tahun",
        "month": "%s Bulan",
        "rate_comment": "Jika Anda suka aplikasi ini, mohon beri penilaian",
        "Lifetime": "Seumur Hidup",
        "off": "%s% DISKON",
        "Privacy": "Kebijakan Privasi",
        "Terms": "Syarat Penggunaan",
        "saved": "Gambar disimpan ke foto",
        "Download": "Unduh",
        "Save to Photos": "Simpan ke Foto",
        "Search": "Cari",
        "Share": "Bagikan",
        "Save": "Simpan",
        "Cancel Anytime": "Batalkan Kapan Saja",
        "Premium": "Premium",
        "pr1": "Buka Premium",
        "pr2": "Akses Penuh",
        "pr3": "Coba Premium",
        "pr4": "Coba Premium Gratis",
        "pr5": "Buka Akses Tak Terbatas",
        "btn1": "Lanjutkan",
        "btn2": "Mulai Uji Coba Gratis",
        "btn3": "Mulai Uji Coba Gratis 3 Hari",
        "btn4": "Mulai Uji Coba Gratis dan Rencana",
        "Watch ad": "Tonton iklan",
        "CONTINUE": "LANJUTKAN",
        "free3": "3 HARI GRATIS",
        "No payment now": "Tidak ada pembayaran sekarang",
        "then": "kemudian",
        "Payment successful": "Pembayaran berhasil",
        "premiumDesc": "Anda sedang menggunakan versi PREMIUM aplikasi ini",
        "Success": "Berhasil",
        "SUCCESS": "BERHASIL",
        "ERROR": "ERROR",
        "Error": "Kesalahan",
        "nosubs": "Anda tidak memiliki langganan aktif.",
        "buyPremium": "✓ Beli Premium",
        "Buy Premium": "Beli Premium",
        "ALERT": "PERINGATAN",
        "Restore Purchases": "Pulihkan Pembelian",
        "premiumuse": "Anda sedang menggunakan versi premium aplikasi ini."
      },
      "nl": {
        "Support Us!": "Steun ons!",
        "partof":
            "Maak deel uit van ons groeiverhaal door ons een beoordeling te geven.",
        "Weekly": "Wekelijks",
        "FREE": "GRATIS",
        "Rate": "Beoordeel",
        "ONE TIME OFFER": "EENMALIG AANBOD",
        "Yearly": "Jaarlijks",
        "Settings": "Instellingen",
        "Remove Limits": "Verwijder Beperkingen",
        "amazingapp": "Bekijk deze geweldige app op",
        "Remaining": "Resterend",
        "Daily Limit": "Dagelijkse Limiet",
        "Share with Friends": "Deel met Vrienden",
        "Rate Us": "Beoordeel Ons",
        "Submit": "Indienen",
        "Loading": "Laden...",
        "1 Week": "1 Week",
        "1 Year": "1 Jaar",
        "month": "%s Maand",
        "rate_comment": "Als je deze app leuk vindt, beoordeel het dan",
        "Lifetime": "Levenslang",
        "off": "%s% KORTING",
        "Privacy": "Privacybeleid",
        "Terms": "Gebruiksvoorwaarden",
        "saved": "Afbeelding opgeslagen in foto's",
        "Download": "Downloaden",
        "Save to Photos": "Opslaan in Foto's",
        "Search": "Zoeken",
        "Share": "Delen",
        "Save": "Opslaan",
        "Cancel Anytime": "Op elk moment annuleren",
        "Premium": "Premium",
        "pr1": "Ontgrendel Premium",
        "pr2": "Volledige Toegang",
        "pr3": "Probeer Premium",
        "pr4": "Probeer Premium Gratis",
        "pr5": "Ontgrendel Onbeperkte Toegang",
        "btn1": "Doorgaan",
        "btn2": "Start Gratis Proefperiode",
        "btn3": "Start 3 Dagen Gratis Proefperiode",
        "btn4": "Begin gratis proefversie en plan",
        "Watch ad": "Bekijk advertentie",
        "CONTINUE": "DOORGAAN",
        "free3": "3 DAGEN GRATIS",
        "No payment now": "Geen betaling nu",
        "then": "dan",
        "Payment successful": "Betaling succesvol",
        "premiumDesc": "Je gebruikt nu de PREMIUM versie van de app",
        "Success": "Succes",
        "SUCCESS": "SUCCES",
        "ERROR": "FOUT",
        "Error": "Fout",
        "nosubs": "Je hebt geen actieve abonnementen.",
        "buyPremium": "✓ Koop Premium",
        "Buy Premium": "Koop Premium",
        "ALERT": "ALERT",
        "Restore Purchases": "Aankopen herstellen",
        "premiumuse": "Je gebruikt de premium versie van deze app."
      }
    };
  }

  static Map<String, Map<String, String>> mergeMaps(
      Map<String, Map<String, String>> map1,
      Map<String, Map<String, String>> map2) {
    Map<String, Map<String, String>> mergedMap = {};

    // Add all entries from map1
    mergedMap.addAll(map1);

    // Merge entries from map2
    map2.forEach((key, value) {
      if (mergedMap.containsKey(key)) {
        // If the key exists in both maps, merge the inner maps
        mergedMap[key]?.addAll(value);
      } else {
        // If the key doesn't exist in the merged map, add it
        mergedMap[key] = value;
      }
    });

    return mergedMap;
  }
}
