// convert to en,  tr , fr , es, de, it, ja, ar, ru, zh , pt , hi , ms , ko , id, nl

class TranslateHelper {
  static Map<String, Map<String, String>> getHelperTranslations() {
    return {
      "en": {
        "Settings": "Settings",
        "Remove Limits": "Remove Limits",
        "Check out this amazing app at": "Check out this amazing app at",
        "Remaining": "Remaining",
        "Daily Limit": "Daily Limit",
        "Share with Friends": "Share with Friends",
        "Rate Us": "Rate Us",
        "1 Week": "1 Week",
        "1 Year": "1 Year",
        "off": "%s% OFF",
        "Privacy Policy": "Privacy Policy",
        "Terms of Use (EULA)": "Terms of Use (EULA)",
        "Image saved to photos": "Image saved to photos",
        "Save to Photos": "Save to Photos",
        "Search": "Search",
        "Share": "Share",
        "Save": "Save",
        "Premium": "Premium",
        "Watch ad": "Watch ad",
        "CONTINUE": "CONTINUE",
        "3 DAYS FREE": "3 DAYS FREE",
        "DISCOUNT": "DISCOUNT",
        "months": "months",
        "month": "month",
        "MOST POPULAR": "MOST POPULAR",
        "then": "then",
        "Payment successful": "Payment successful",
        "You are using PREMIUM version of app now":
            "You are using PREMIUM version of app now",
        "Success": "Success",
        "SUCCESS": "SUCCESS",
        "ERROR": "ERROR",
        "Error": "Error",
        "You have no active subscription.": "You have no active subscription.",
        "Buy Premium": "Buy Premium",
        "Restore Purchases": "Restore Purchases",
        "You are using the premium version of this app.":
            "You are using the premium version of this app."
      },
      "tr": {
        "Settings": "Ayarlar",
        "Remove Limits": "Sınırlamaları Kaldır",
        "Check out this amazing app at":
            "Bu harika uygulamayı şuradan kontrol edin",
        "Remaining": "Kalan",
        "Daily Limit": "Günlük Limit",
        "Share with Friends": "Arkadaşlarla Paylaş",
        "Rate Us": "Bizi Değerlendir",
        "1 Week": "1 Hafta",
        "1 Year": "1 Yıl",
        "off": "İndirimli: %s%",
        "Privacy Policy": "Gizlilik Politikası",
        "Terms of Use (EULA)": "Kullanım Koşulları (EULA)",
        "Image saved to photos": "Resim fotoğraflara kaydedildi",
        "Save to Photos": "Fotoğraflara Kaydet",
        "Search": "Ara",
        "Share": "Paylaş",
        "Save": "Kaydet",
        "Premium": "Premium",
        "Watch ad": "Reklam İzle",
        "CONTINUE": "DEVAM",
        "3 DAYS FREE": "3 GÜN ÜCRETSİZ",
        "DISCOUNT": "İNDİRİM",
        "months": "aylar",
        "month": "ay",
        "MOST POPULAR": "EN POPÜLER",
        "then": "sonra",
        "Payment successful": "Ödeme başarılı",
        "You are using PREMIUM version of app now":
            "Şu anda uygulamanın PREMIUM sürümünü kullanıyorsunuz",
        "Success": "Başarılı",
        "SUCCESS": "BAŞARILI",
        "ERROR": "HATA",
        "Error": "Hata",
        "You have no active subscription.":
            "Aktif bir aboneliğiniz bulunmamaktadır.",
        "Buy Premium": "Premium Satın Al",
        "Restore Purchases": "Satın Alımları Geri Yükle",
        "You are using the premium version of this app.":
            "Bu uygulamanın premium sürümünü kullanıyorsunuz."
      },
      "fr": {
        "Settings": "Paramètres",
        "Remove Limits": "Supprimer les Limites",
        "Check out this amazing app at":
            "Découvrez cette incroyable application sur",
        "Remaining": "Restant",
        "Daily Limit": "Limite quotidienne",
        "Share with Friends": "Partager avec des amis",
        "Rate Us": "Évaluez-nous",
        "1 Week": "1 semaine",
        "1 Year": "1 an",
        "off": "%s% DE RÉDUCTION",
        "Privacy Policy": "Politique de confidentialité",
        "Terms of Use (EULA)": "Conditions d'utilisation (CLUF)",
        "Image saved to photos": "Image enregistrée dans les photos",
        "Save to Photos": "Enregistrer dans les photos",
        "Search": "Rechercher",
        "Share": "Partager",
        "Save": "Enregistrer",
        "Premium": "Premium",
        "Watch ad": "Regarder une publicité",
        "CONTINUE": "CONTINUER",
        "3 DAYS FREE": "3 JOURS GRATUITS",
        "DISCOUNT": "RÉDUCTION",
        "months": "mois",
        "month": "mois",
        "MOST POPULAR": "LE PLUS POPULAIRE",
        "then": "ensuite",
        "Payment successful": "Paiement réussi",
        "You are using PREMIUM version of app now":
            "Vous utilisez actuellement la version PREMIUM de l'application",
        "Success": "Succès",
        "SUCCESS": "SUCCÈS",
        "ERROR": "ERREUR",
        "Error": "Erreur",
        "You have no active subscription.":
            "Vous n'avez aucune souscription active.",
        "Buy Premium": "Acheter Premium",
        "Restore Purchases": "Restaurer les achats",
        "You are using the premium version of this app.":
            "Vous utilisez la version premium de cette application."
      },
      "es": {
        "Settings": "Configuración",
        "Remove Limits": "Eliminar Límites",
        "Check out this amazing app at":
            "Echa un vistazo a esta increíble aplicación en",
        "Remaining": "Restante",
        "Daily Limit": "Límite Diario",
        "Share with Friends": "Compartir con Amigos",
        "Rate Us": "Califícanos",
        "1 Week": "1 Semana",
        "1 Year": "1 Año",
        "off": "%s% DE DESCUENTO",
        "Privacy Policy": "Política de Privacidad",
        "Terms of Use (EULA)": "Términos de Uso (EULA)",
        "Image saved to photos": "Imagen guardada en fotos",
        "Save to Photos": "Guardar en Fotos",
        "Search": "Buscar",
        "Share": "Compartir",
        "Save": "Guardar",
        "Premium": "Premium",
        "Watch ad": "Ver anuncio",
        "CONTINUE": "CONTINUAR",
        "3 DAYS FREE": "3 DÍAS GRATIS",
        "DISCOUNT": "DESCUENTO",
        "months": "meses",
        "month": "mes",
        "MOST POPULAR": "MÁS POPULAR",
        "then": "luego",
        "Payment successful": "Pago exitoso",
        "You are using PREMIUM version of app now":
            "Estás utilizando la versión PREMIUM de esta aplicación ahora",
        "Success": "Éxito",
        "SUCCESS": "ÉXITO",
        "ERROR": "ERROR",
        "Error": "Error",
        "You have no active subscription.": "No tienes una suscripción activa.",
        "Buy Premium": "Comprar Premium",
        "Restore Purchases": "Restaurar Compras",
        "You are using the premium version of this app.":
            "Estás utilizando la versión premium de esta aplicación."
      },
      "de": {
        "Settings": "Einstellungen",
        "Remove Limits": "Grenzen entfernen",
        "Check out this amazing app at":
            "Schau dir diese fantastische App an unter",
        "Remaining": "Verbleibend",
        "Daily Limit": "Tageslimit",
        "Share with Friends": "Mit Freunden teilen",
        "Rate Us": "Bewerte uns",
        "1 Week": "1 Woche",
        "1 Year": "1 Jahr",
        "off": "%s% RABATT",
        "Privacy Policy": "Datenschutzbestimmungen",
        "Terms of Use (EULA)": "Nutzungsbedingungen (EULA)",
        "Image saved to photos": "Bild in Fotos gespeichert",
        "Save to Photos": "In Fotos speichern",
        "Search": "Suche",
        "Share": "Teilen",
        "Save": "Speichern",
        "Premium": "Premium",
        "Watch ad": "Werbung ansehen",
        "CONTINUE": "WEITER",
        "3 DAYS FREE": "3 TAGE GRATIS",
        "DISCOUNT": "RABATT",
        "months": "Monate",
        "month": "Monat",
        "MOST POPULAR": "AM BELIEBTESTEN",
        "then": "dann",
        "Payment successful": "Zahlung erfolgreich",
        "You are using PREMIUM version of app now":
            "Du verwendest jetzt die PREMIUM-Version dieser App",
        "Success": "Erfolg",
        "SUCCESS": "ERFOLG",
        "ERROR": "FEHLER",
        "Error": "Fehler",
        "You have no active subscription.": "Du hast kein aktives Abonnement.",
        "Buy Premium": "Premium kaufen",
        "Restore Purchases": "Käufe wiederherstellen",
        "You are using the premium version of this app.":
            "Du verwendest die Premium-Version dieser App."
      },
      "it": {
        "Settings": "Impostazioni",
        "Remove Limits": "Rimuovi Limiti",
        "Check out this amazing app at": "Scopri questa incredibile app su",
        "Remaining": "Rimanente",
        "Daily Limit": "Limite giornaliero",
        "Share with Friends": "Condividi con gli amici",
        "Rate Us": "Valutaci",
        "1 Week": "1 Settimana",
        "1 Year": "1 Anno",
        "off": "Sconto del %s%",
        "Privacy Policy": "Informativa sulla Privacy",
        "Terms of Use (EULA)": "Termini di Utilizzo (EULA)",
        "Image saved to photos": "Immagine salvata nelle foto",
        "Save to Photos": "Salva nelle Foto",
        "Search": "Cerca",
        "Share": "Condividi",
        "Save": "Salva",
        "Premium": "Premium",
        "Watch ad": "Guarda annuncio",
        "CONTINUE": "CONTINUA",
        "3 DAYS FREE": "3 GIORNI GRATIS",
        "DISCOUNT": "SCONTI",
        "months": "mesi",
        "month": "mese",
        "MOST POPULAR": "PIÙ POPOLARE",
        "then": "poi",
        "Payment successful": "Pagamento effettuato con successo",
        "You are using PREMIUM version of app now":
            "Stai utilizzando la versione PREMIUM di questa app",
        "Success": "Successo",
        "SUCCESS": "SUCCESSO",
        "ERROR": "ERRORE",
        "Error": "Errore",
        "You have no active subscription.":
            "Non hai una sottoscrizione attiva.",
        "Buy Premium": "Acquista Premium",
        "Restore Purchases": "Ripristina Acquisti",
        "You are using the premium version of this app.":
            "Stai utilizzando la versione premium di questa app."
      },
      "ja": {
        "Settings": "設定",
        "Remove Limits": "制限を解除",
        "Check out this amazing app at": "この素晴らしいアプリをチェックしてください",
        "Remaining": "残り",
        "Daily Limit": "毎日の制限",
        "Share with Friends": "友達と共有",
        "Rate Us": "評価する",
        "1 Week": "1週間",
        "1 Year": "1年",
        "off": "%s% OFF",
        "Privacy Policy": "プライバシーポリシー",
        "Terms of Use (EULA)": "利用規約（EULA）",
        "Image saved to photos": "画像が写真に保存されました",
        "Save to Photos": "写真に保存",
        "Search": "検索",
        "Share": "共有",
        "Save": "保存",
        "Premium": "プレミアム",
        "Watch ad": "広告を視聴",
        "CONTINUE": "続行",
        "3 DAYS FREE": "3日間無料",
        "DISCOUNT": "割引",
        "months": "ヶ月",
        "month": "月",
        "MOST POPULAR": "最も人気のある",
        "then": "その後",
        "Payment successful": "支払いが成功しました",
        "You are using PREMIUM version of app now": "現在、アプリのプレミアムバージョンを使用しています",
        "Success": "成功",
        "SUCCESS": "成功",
        "ERROR": "エラー",
        "Error": "エラー",
        "You have no active subscription.": "アクティブな購読はありません。",
        "Buy Premium": "プレミアムを購入",
        "Restore Purchases": "購入を復元",
        "You are using the premium version of this app.":
            "このアプリのプレミアムバージョンを使用しています。"
      },
      "ar": {
        "Settings": "الإعدادات",
        "Remove Limits": "إزالة الحدود",
        "Check out this amazing app at": "تحقق من هذا التطبيق المذهل في",
        "Remaining": "المتبقي",
        "Daily Limit": "الحد اليومي",
        "Share with Friends": "مشاركة مع الأصدقاء",
        "Rate Us": "قيّمنا",
        "1 Week": "1 أسبوع",
        "1 Year": "1 سنة",
        "off": "%s% خصم",
        "Privacy Policy": "سياسة الخصوصية",
        "Terms of Use (EULA)": "شروط الاستخدام (EULA)",
        "Image saved to photos": "تم حفظ الصورة في الصور",
        "Save to Photos": "حفظ في الصور",
        "Search": "بحث",
        "Share": "مشاركة",
        "Save": "حفظ",
        "Premium": "بريميوم",
        "Watch ad": "مشاهدة إعلان",
        "CONTINUE": "استمر",
        "3 DAYS FREE": "3 أيام مجاناً",
        "DISCOUNT": "خصم",
        "months": "أشهر",
        "month": "شهر",
        "MOST POPULAR": "الأكثر شيوعًا",
        "then": "ثم",
        "Payment successful": "تم الدفع بنجاح",
        "You are using PREMIUM version of app now":
            "أنت تستخدم النسخة المميزة من التطبيق الآن",
        "Success": "نجاح",
        "SUCCESS": "نجاح",
        "ERROR": "خطأ",
        "Error": "خطأ",
        "You have no active subscription.": "ليس لديك اشتراك نشط.",
        "Buy Premium": "شراء النسخة المميزة",
        "Restore Purchases": "استعادة المشتريات",
        "You are using the premium version of this app.":
            "أنت تستخدم النسخة المميزة من هذا التطبيق."
      },
      "ru": {
        "Settings": "Настройки",
        "Remove Limits": "Удалить ограничения",
        "Check out this amazing app at":
            "Ознакомьтесь с этим удивительным приложением по адресу",
        "Remaining": "Осталось",
        "Daily Limit": "Ежедневный лимит",
        "Share with Friends": "Поделиться с друзьями",
        "Rate Us": "Оцените нас",
        "1 Week": "1 неделя",
        "1 Year": "1 год",
        "off": "СКИДКА %s%",
        "Privacy Policy": "Политика конфиденциальности",
        "Terms of Use (EULA)": "Условия использования (EULA)",
        "Image saved to photos": "Изображение сохранено в фотографиях",
        "Save to Photos": "Сохранить в Фотографиях",
        "Search": "Поиск",
        "Share": "Поделиться",
        "Save": "Сохранить",
        "Premium": "Премиум",
        "Watch ad": "Смотреть рекламу",
        "CONTINUE": "ПРОДОЛЖИТЬ",
        "3 DAYS FREE": "3 ДНЯ БЕСПЛАТНО",
        "DISCOUNT": "СКИДКА",
        "months": "месяцев",
        "month": "месяц",
        "MOST POPULAR": "САМОЕ ПОПУЛЯРНОЕ",
        "then": "затем",
        "Payment successful": "Оплата прошла успешно",
        "You are using PREMIUM version of app now":
            "Вы сейчас используете ПРЕМИУМ-версию приложения",
        "Success": "Успех",
        "SUCCESS": "УСПЕХ",
        "ERROR": "ОШИБКА",
        "Error": "Ошибка",
        "You have no active subscription.": "У вас нет активной подписки.",
        "Buy Premium": "Купить Премиум",
        "Restore Purchases": "Восстановить покупки",
        "You are using the premium version of this app.":
            "Вы используете премиум-версию этого приложения."
      },
      "zh": {
        "Settings": "设置",
        "Remove Limits": "解除限制",
        "Check out this amazing app at": "在这个惊人的应用程序中查看",
        "Remaining": "剩余",
        "Daily Limit": "每日限额",
        "Share with Friends": "与朋友分享",
        "Rate Us": "给我们评分",
        "1 Week": "1周",
        "1 Year": "1年",
        "off": "折扣%s%",
        "Privacy Policy": "隐私政策",
        "Terms of Use (EULA)": "使用条款 (EULA)",
        "Image saved to photos": "图片保存到照片",
        "Save to Photos": "保存到照片",
        "Search": "搜索",
        "Share": "分享",
        "Save": "保存",
        "Premium": "高级版",
        "Watch ad": "观看广告",
        "CONTINUE": "继续",
        "3 DAYS FREE": "免费3天",
        "DISCOUNT": "折扣",
        "months": "个月",
        "month": "个月",
        "MOST POPULAR": "最受欢迎",
        "then": "然后",
        "Payment successful": "支付成功",
        "You are using PREMIUM version of app now": "您现在正在使用该应用的高级版",
        "Success": "成功",
        "SUCCESS": "成功",
        "ERROR": "错误",
        "Error": "错误",
        "You have no active subscription.": "您没有有效的订阅。",
        "Buy Premium": "购买高级版",
        "Restore Purchases": "恢复购买",
        "You are using the premium version of this app.": "您正在使用该应用的高级版。"
      },
      "pt": {
        "Settings": "Configurações",
        "Remove Limits": "Remover Limites",
        "Check out this amazing app at": "Confira este incrível aplicativo em",
        "Remaining": "Restante",
        "Daily Limit": "Limite Diário",
        "Share with Friends": "Compartilhar com Amigos",
        "Rate Us": "Avalie-nos",
        "1 Week": "1 Semana",
        "1 Year": "1 Ano",
        "off": "%s% DE DESCONTO",
        "Privacy Policy": "Política de Privacidade",
        "Terms of Use (EULA)": "Termos de Uso (EULA)",
        "Image saved to photos": "Imagem salva nas fotos",
        "Save to Photos": "Salvar nas Fotos",
        "Search": "Buscar",
        "Share": "Compartilhar",
        "Save": "Salvar",
        "Premium": "Premium",
        "Watch ad": "Assistir anúncio",
        "CONTINUE": "CONTINUAR",
        "3 DAYS FREE": "3 DIAS GRÁTIS",
        "DISCOUNT": "DESCONTO",
        "months": "meses",
        "month": "mês",
        "MOST POPULAR": "MAIS POPULAR",
        "then": "então",
        "Payment successful": "Pagamento efetuado com sucesso",
        "You are using PREMIUM version of app now":
            "Você está usando a versão PREMIUM deste aplicativo agora",
        "Success": "Sucesso",
        "SUCCESS": "SUCESSO",
        "ERROR": "ERRO",
        "Error": "Erro",
        "You have no active subscription.":
            "Você não possui uma assinatura ativa.",
        "Buy Premium": "Comprar Premium",
        "Restore Purchases": "Restaurar Compras",
        "You are using the premium version of this app.":
            "Você está usando a versão premium deste aplicativo."
      },
      "hi": {
        "Settings": "सेटिंग्स",
        "Remove Limits": "सीमा हटाएं",
        "Check out this amazing app at": "इस शानदार ऐप की जांच करें",
        "Remaining": "शेष",
        "Daily Limit": "दैनिक सीमा",
        "Share with Friends": "दोस्तों के साथ साझा करें",
        "Rate Us": "हमें रेट करें",
        "1 Week": "1 सप्ताह",
        "1 Year": "1 वर्ष",
        "off": "%s% छूट",
        "Privacy Policy": "गोपनीयता नीति",
        "Terms of Use (EULA)": "उपयोग की शर्तें (EULA)",
        "Image saved to photos": "चित्र तस्वीरों में सहेजा गया",
        "Save to Photos": "फ़ोटोज़ में सहेजें",
        "Search": "खोजें",
        "Share": "साझा करें",
        "Save": "सहेजें",
        "Premium": "प्रीमियम",
        "Watch ad": "विज्ञापन देखें",
        "CONTINUE": "जारी रखें",
        "3 DAYS FREE": "3 दिन मुफ्त",
        "DISCOUNT": "छूट",
        "months": "महीने",
        "month": "महीना",
        "MOST POPULAR": "सबसे लोकप्रिय",
        "then": "फिर",
        "Payment successful": "भुगतान सफल",
        "You are using PREMIUM version of app now":
            "आप अब ऐप के प्रीमियम संस्करण का उपयोग कर रहे हैं",
        "Success": "सफलता",
        "SUCCESS": "सफलता",
        "ERROR": "त्रुटि",
        "Error": "त्रुटि",
        "You have no active subscription.": "आपका कोई सक्रिय सदस्यता नहीं है।",
        "Buy Premium": "प्रीमियम खरीदें",
        "Restore Purchases": "खरीदारी को पुनर्स्थापित करें",
        "You are using the premium version of this app.":
            "आप इस ऐप के प्रीमियम संस्करण का उपयोग कर रहे हैं।"
      },
      "ms": {
        "Settings": "Tetapan",
        "Remove Limits": "Alihkan Had",
        "Check out this amazing app at": "Semak aplikasi menakjubkan ini di",
        "Remaining": "Baki",
        "Daily Limit": "Had Harian",
        "Share with Friends": "Kongsi dengan Rakan",
        "Rate Us": "Beri Kami Penilaian",
        "1 Week": "1 Minggu",
        "1 Year": "1 Tahun",
        "off": "DISKAUN %s%",
        "Privacy Policy": "Dasar Privasi",
        "Terms of Use (EULA)": "Terma Penggunaan (EULA)",
        "Image saved to photos": "Gambar disimpan ke foto",
        "Save to Photos": "Simpan ke Foto",
        "Search": "Carian",
        "Share": "Kongsi",
        "Save": "Simpan",
        "Premium": "Premium",
        "Watch ad": "Tonton iklan",
        "CONTINUE": "TERUSKAN",
        "3 DAYS FREE": "3 HARI PERCUMA",
        "DISCOUNT": "DISKAUN",
        "months": "bulan",
        "month": "bulan",
        "MOST POPULAR": "PALING POPULAR",
        "then": "kemudian",
        "Payment successful": "Pembayaran berjaya",
        "You are using PREMIUM version of app now":
            "Anda kini menggunakan versi PREMIUM aplikasi ini",
        "Success": "Berjaya",
        "SUCCESS": "BERJAYA",
        "ERROR": "RALAT",
        "Error": "Ralat",
        "You have no active subscription.": "Anda tiada langganan aktif.",
        "Buy Premium": "Beli Premium",
        "Restore Purchases": "Pulihkan Pembelian",
        "You are using the premium version of this app.":
            "Anda menggunakan versi premium aplikasi ini."
      },
      "ko": {
        "Settings": "설정",
        "Remove Limits": "제한 해제",
        "Check out this amazing app at": "이 멋진 앱을 확인하세요",
        "Remaining": "남은 시간",
        "Daily Limit": "일일 한도",
        "Share with Friends": "친구와 공유하기",
        "Rate Us": "평가하기",
        "1 Week": "1주일",
        "1 Year": "1년",
        "off": "%s% 할인",
        "Privacy Policy": "개인 정보 정책",
        "Terms of Use (EULA)": "이용 약관 (EULA)",
        "Image saved to photos": "이미지가 사진에 저장되었습니다",
        "Save to Photos": "사진에 저장",
        "Search": "검색",
        "Share": "공유",
        "Save": "저장",
        "Premium": "프리미엄",
        "Watch ad": "광고 시청",
        "CONTINUE": "계속",
        "3 DAYS FREE": "3일 무료",
        "DISCOUNT": "할인",
        "months": "개월",
        "month": "개월",
        "MOST POPULAR": "가장 인기 있는",
        "then": "그런 다음",
        "Payment successful": "결제가 성공적으로 이루어졌습니다",
        "You are using PREMIUM version of app now": "지금 앱의 프리미엄 버전을 사용 중입니다",
        "Success": "성공",
        "SUCCESS": "성공",
        "ERROR": "오류",
        "Error": "오류",
        "You have no active subscription.": "활성 구독이 없습니다.",
        "Buy Premium": "프리미엄 구매",
        "Restore Purchases": "구매 복원",
        "You are using the premium version of this app.":
            "이 앱의 프리미엄 버전을 사용 중입니다."
      },
      "id": {
        "Settings": "Pengaturan",
        "Remove Limits": "Hapus Batasan",
        "Check out this amazing app at": "Cek aplikasi menakjubkan ini di",
        "Remaining": "Sisa",
        "Daily Limit": "Batas Harian",
        "Share with Friends": "Bagikan dengan Teman",
        "Rate Us": "Beri Rating",
        "1 Week": "1 Minggu",
        "1 Year": "1 Tahun",
        "off": "Diskon %s%",
        "Privacy Policy": "Kebijakan Privasi",
        "Terms of Use (EULA)": "Syarat Penggunaan (EULA)",
        "Image saved to photos": "Gambar disimpan ke foto",
        "Save to Photos": "Simpan ke Foto",
        "Search": "Cari",
        "Share": "Bagikan",
        "Save": "Simpan",
        "Premium": "Premium",
        "Watch ad": "Tonton iklan",
        "CONTINUE": "LANJUTKAN",
        "3 DAYS FREE": "3 HARI GRATIS",
        "DISCOUNT": "DISKON",
        "months": "bulan",
        "month": "bulan",
        "MOST POPULAR": "PALING POPULER",
        "then": "kemudian",
        "Payment successful": "Pembayaran berhasil",
        "You are using PREMIUM version of app now":
            "Anda sekarang menggunakan versi PREMIUM dari aplikasi ini",
        "Success": "Sukses",
        "SUCCESS": "SUKSES",
        "ERROR": "ERROR",
        "Error": "Error",
        "You have no active subscription.":
            "Anda tidak memiliki langganan aktif.",
        "Buy Premium": "Beli Premium",
        "Restore Purchases": "Pulihkan Pembelian",
        "You are using the premium version of this app.":
            "Anda menggunakan versi premium dari aplikasi ini."
      },
      "nl": {
        "Settings": "Instellingen",
        "Remove Limits": "Beperkingen opheffen",
        "Check out this amazing app at": "Bekijk deze geweldige app op",
        "Remaining": "Resterend",
        "Daily Limit": "Dagelijkse limiet",
        "Share with Friends": "Delen met vrienden",
        "Rate Us": "Beoordeel ons",
        "1 Week": "1 week",
        "1 Year": "1 jaar",
        "off": "%s% KORTING",
        "Privacy Policy": "Privacybeleid",
        "Terms of Use (EULA)": "Gebruiksvoorwaarden (EULA)",
        "Image saved to photos": "Afbeelding opgeslagen in foto's",
        "Save to Photos": "Opslaan in Foto's",
        "Search": "Zoeken",
        "Share": "Delen",
        "Save": "Opslaan",
        "Premium": "Premium",
        "Watch ad": "Bekijk advertentie",
        "CONTINUE": "DOORGAAN",
        "3 DAYS FREE": "3 DAGEN GRATIS",
        "DISCOUNT": "KORTING",
        "months": "maanden",
        "month": "maand",
        "MOST POPULAR": "MEEST POPULAIR",
        "then": "dan",
        "Payment successful": "Betaling gelukt",
        "You are using PREMIUM version of app now":
            "Je gebruikt nu de PREMIUM-versie van deze app",
        "Success": "Succes",
        "SUCCESS": "SUCCES",
        "ERROR": "FOUT",
        "Error": "Fout",
        "You have no active subscription.": "Je hebt geen actief abonnement.",
        "Buy Premium": "Koop Premium",
        "Restore Purchases": "Aankopen herstellen",
        "You are using the premium version of this app.":
            "Je gebruikt de premiumversie van deze app."
      }
    };
  }

  static Map<String, Map<String, String>> mergeMaps(
      Map<String, Map<String, String>> map1,
      Map<String, Map<String, String>> map2) {
    Map<String, Map<String, String>> mergedMap = {};

    // Add all entries from map1
    mergedMap.addAll(map1);

    // Merge entries from map2
    map2.forEach((key, value) {
      if (mergedMap.containsKey(key)) {
        // If the key exists in both maps, merge the inner maps
        mergedMap[key]?.addAll(value);
      } else {
        // If the key doesn't exist in the merged map, add it
        mergedMap[key] = value;
      }
    });

    return mergedMap;
  }
}
